; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  			; 1  
	const DEX_IVYSAUR    			; 2  
	const DEX_VENUSAUR   			; 3  
	const DEX_M_VENUSAUR			; 4  
	const DEX_CHARMANDER 			; 5  
	const DEX_CHARMELEON 			; 6  
	const DEX_CHARIZARD  			; 7  
	const DEX_M_CHARIZARDX		; 8  
	const DEX_M_CHARIZARDY		; 9  
	const DEX_SQUIRTLE   			; 10 
	const DEX_WARTORTLE  			; 11 
	const DEX_BLASTOISE  			; 12 
	const DEX_M_BLASTOISE			; 13 
	const DEX_CATERPIE   			; 14 
	const DEX_METAPOD    			; 15 
	const DEX_BUTTERFREE 			; 16 
	const DEX_WEEDLE     			; 17 
	const DEX_KAKUNA     			; 18 
	const DEX_BEEDRILL   			; 19 
	const DEX_M_BEEDRILL			; 20 
	const DEX_PIDGEY     			; 21 
	const DEX_PIDGEOTTO  			; 22 
	const DEX_PIDGEOT    			; 23 
	const DEX_M_PIDGEOT				; 24 
	const DEX_RATTATA    			; 25 
	const DEX_RATICATE   			; 26 
	const DEX_SPEAROW    			; 27 
	const DEX_FEAROW     			; 28 
	const DEX_EKANS      			; 29 
	const DEX_ARBOK      			; 30 
	const DEX_PICHU			 			; 31 
	const DEX_PIKACHU    			; 32 
	const DEX_RAICHU     			; 33 
	const DEX_M_RAICHUX				; 34 
	const DEX_M_RAICHUY				; 35 
	const DEX_SANDSHREW  			; 36 
	const DEX_SANDSLASH  			; 37 
	const DEX_M_SANDSLASH			; 38 
	const DEX_I_SANDSHREW			; 39 
	const DEX_I_SANDSLASH			; 40 
	const DEX_NIDORAN_F  			; 41 
	const DEX_NIDORINA   			; 42 
	const DEX_NIDOQUEEN  			; 43 
	const DEX_NIDORAN_M  			; 44 
	const DEX_NIDORINO   			; 45 
	const DEX_NIDOKING   			; 46 
	const DEX_CLEFFA		 			; 47 
	const DEX_CLEFAIRY   			; 48 
	const DEX_CLEFABLE   			; 49 
	const DEX_VULPIX     			; 50 
	const DEX_NINETALES  			; 51 
	const DEX_I_VULPIX	 			; 52 
	const DEX_I_NINETALES			; 53 
	const DEX_IGGLYBUFF	 			; 54 
	const DEX_JIGGLYPUFF 			; 55 
	const DEX_WIGGLYTUFF 			; 56 
	const DEX_ZUBAT      			; 57 
	const DEX_GOLBAT     			; 58 
	const DEX_CROBAT		 			; 59 
	const DEX_ODDISH     			; 60 
	const DEX_GLOOM      			; 61 
	const DEX_VILEPLUME  			; 62 
	const DEX_BELLOSSOM	 			; 63 
	const DEX_PARAS      			; 64 
	const DEX_PARASECT   			; 65 
	const DEX_VENONAT    			; 66 
	const DEX_VENOMOTH   			; 67 
	const DEX_DIGLETT    			; 68 
	const DEX_DUGTRIO    			; 69 
	const DEX_MEOWTH     			; 70 
	const DEX_PERSIAN    			; 71 
	const DEX_PSYDUCK    			; 72 
	const DEX_GOLDUCK    			; 73 
	const DEX_MANKEY     			; 74 
	const DEX_PRIMEAPE   			; 75 
	const DEX_ANNIHILAPE 			; 76 
	const DEX_GROWLITHE  			; 77 
	const DEX_ARCANINE   			; 78 
	const DEX_POLIWAG    			; 79 
	const DEX_POLIWHIRL  			; 80 
	const DEX_POLIWRATH  			; 81 
	const DEX_POLITOED	 			; 82 
	const DEX_ABRA       			; 83 
	const DEX_KADABRA    			; 84 
	const DEX_ALAKAZAM   			; 85 
	const DEX_M_ALAKAZAM			; 86 
	const DEX_MACHOP     			; 87 
	const DEX_MACHOKE    			; 88 
	const DEX_MACHAMP    			; 89 
	const DEX_M_MACHAMP			 	; 90 
	const DEX_BELLSPROUT 			; 91 
	const DEX_WEEPINBELL 			; 92 
	const DEX_VICTREEBEL 			; 93 
	const DEX_M_VICTREEBEL		; 94 
	const DEX_TENTACOOL  			; 95 
	const DEX_TENTACRUEL 			; 96 
	const DEX_GEODUDE    			; 97 
	const DEX_GRAVELER   			; 98 
	const DEX_GOLEM      			; 99 
	const DEX_PONYTA     			; 100
	const DEX_RAPIDASH   			; 101
	const DEX_P_PONYTA	 			; 102
	const DEX_P_RAPIDASH 			; 103
	const DEX_SLOWPOKE   			; 104
	const DEX_SLOWBRO    			; 105
	const DEX_M_SLOWBRO				; 106
	const DEX_SLOWKING	 			; 107
	const DEX_MAGNEMITE  			; 108
	const DEX_MAGNETON   			; 109
	const DEX_MAGNEZONE	 			; 110
	const DEX_FARFETCHD  			; 111
	const DEX_SIRFETCHD				; 112
	const DEX_DODUO      			; 113
	const DEX_DODRIO     			; 114
	const DEX_SEEL       			; 115
	const DEX_DEWGONG    			; 116
	const DEX_NARCTIC		 			; 117
	const DEX_GRIMER     			; 118
	const DEX_MUK        			; 119
	const DEX_SHELLDER   			; 120
	const DEX_CLOYSTER   			; 121
	const DEX_GASTLY     			; 122
	const DEX_HAUNTER    			; 123
	const DEX_GENGAR     			; 124
	const DEX_M_GENGAR				; 125
	const DEX_ONIX       			; 126
	const DEX_CRYSTALIX	 			; 127
	const DEX_M_CRYSTALIX			; 128
	const DEX_DROWZEE    			; 129
	const DEX_HYPNO      			; 130
	const DEX_KRABBY     			; 131
	const DEX_KINGLER    			; 132
	const DEX_VOLTORB    			; 133
	const DEX_ELECTRODE  			; 134
	const DEX_EXEGGCUTE  			; 135
	const DEX_EXEGGUTOR  			; 136
	const DEX_CUBONE     			; 137
	const DEX_MAROWAK    			; 138
	const DEX_G_CUBONE	 			; 139
	const DEX_G_MAROWAK	 			; 140
	const DEX_TYROGUE		 			; 141
	const DEX_HITMONLEE  			; 142
	const DEX_HITMONCHAN 			; 143
	const DEX_HITMONTOP	 			; 144
	const DEX_LICKITUNG  			; 145
	const DEX_LICKILICKY 			; 146
	const DEX_KOFFING    			; 147
	const DEX_WEEZING    			; 148
	const DEX_RHYHORN    			; 149
	const DEX_RHYDON     			; 150
	const DEX_RHYPERIOR	 			; 151
	const DEX_HAPPINY		 			; 152
	const DEX_CHANSEY    			; 153
	const DEX_BLISSEY		 			; 154
	const DEX_TANGELA    			; 155
	const DEX_TANGROWTH	 			; 156
	const DEX_KANGASKHAN 			; 157
	const DEX_M_KANGASKHAN		; 158
	const DEX_HORSEA     			; 159
	const DEX_SEADRA     			; 160
	const DEX_KINGDRA		 			; 161
	const DEX_GOLDEEN    			; 162
	const DEX_SEAKING    			; 163
	const DEX_STARYU     			; 164
	const DEX_STARMIE    			; 165
	const DEX_MIME_JR					; 166
	const DEX_MR_MIME    			; 167
	const DEX_SR_MIME		 			; 168
	const DEX_SCYTHER    			; 169
	const DEX_SCIZOR		 			; 170
	const DEX_M_SCIZOR				; 171
	const DEX_KLEAVOR		 			; 172
	const DEX_SMOOCHUM	 			; 173
	const DEX_JYNX       			; 174
	const DEX_ELEKID		 			; 175
	const DEX_ELECTABUZZ 			; 176
	const DEX_ELECTIVIRE 			; 177
	const DEX_MAGBY			 			; 178
	const DEX_MAGMAR     			; 179
	const DEX_MAGMORTAR	 			; 180
	const DEX_PINSIR     			; 181
	const DEX_M_PINSIR				; 182
	const DEX_TAUROS     			; 183
	const DEX_MAGIKARP   			; 184
	const DEX_GYARADOS   			; 185
	const DEX_M_GYARADOS			; 186
	const DEX_LAPRAS     			; 187
	const DEX_M_LAPRAS				; 188
	const DEX_DITTO      			; 189
	const DEX_EEVEE      			; 190
	const DEX_VAPOREON   			; 191
	const DEX_JOLTEON    			; 192
	const DEX_FLAREON    			; 193
	const DEX_ESPEON					; 194
	const DEX_LEAFEON		 			; 195
	const DEX_GLACEON		 			; 196
	const DEX_DRAKEON		 			; 197
	const DEX_PORYGON    			; 198
	const DEX_PORYGON2				; 199
	const DEX_PORYGONZ				; 200
	const DEX_OMANYTE    			; 201
	const DEX_OMASTAR    			; 202
	const DEX_KABUTO     			; 203
	const DEX_KABUTOPS   			; 204
	const DEX_AERODACTYL 			; 205
	const DEX_M_AERODACTYL		; 206
	const DEX_MUNCHLAX	 			; 207
	const DEX_SNORLAX    			; 208
	const DEX_DRATINI    			; 209
	const DEX_DRAGONAIR  			; 210
	const DEX_DRAGONITE  			; 211
	const DEX_M_DRAGONITE			; 212
	const DEX_HONEDGE		 			; 213
	const DEX_DOUBLADE	 			; 214
	const DEX_AEGISLASH	 			; 215
	const DEX_MIMIKYU		 			; 216
	const DEX_ARTICUNO   			; 217
	const DEX_ZAPDOS     			; 218
	const DEX_MOLTRES    			; 219
	const DEX_MISSINGNO			 	; 220
	const DEX_KYOGRE					; 221
	const DEX_GROUDON					; 222
	const DEX_RAYQUAZA				; 223
	const DEX_GIRATINA				; 224
	const DEX_SHAYMIN					; 225
	const DEX_ARCEUS					; 226
	const DEX_TORNADUS				; 227
	const DEX_GENESECT				; 228
	const DEX_DIANCIE					; 229
	const DEX_MARSHADOW			 	; 230
	const DEX_MEWTWO     			; 231
	const DEX_MEW        			; 232

DEF NUM_POKEMON EQU const_value - 1
